### ISSUE TITLE
simulating tmux and screen functionality

### ISSUE THREAD

**Issue by drewlesueur** [kr/pty#37]
Thanks for this library. I am trying to simulate tmux/screen/ssh style functionality.

I have a slightly modified version of the README example:

         func main() {
                 c := exec.Command("/bin/bash")
                 f, err := pty.Start(c)
                 if err != nil {
                         panic(err)
                 }
                 go io.Copy(f, os.Stdin)
                 //go io.Copy(os.Stderr, f)
                 io.Copy(os.Stdout, f)
                 log.Println("this test!")
         }

This seems to work except for when I use the arrow keys, or when I try to open vim.
When I use the arrow keys I see `^[[A` , etc.
Is there something I am doing wrong?

**Comment by creack** [comment]
You need to change your line discipline/termcaps. You probably just want to use the raw mode.
You can use something like this:
- https://github.com/creack/termios/blob/master/raw/raw.go#L49
- https://godoc.org/golang.org/x/crypto/ssh/terminal
- https://github.com/docker/docker/blob/master/pkg/term/term.go#L114

**Comment by drewlesueur** [comment]
Thank you! I will look in to these.

**Comment by drewlesueur** [comment]
Thanks again. With your help, I was able to get what I wanted like this:

        package main

        import (
                "github.com/kr/pty"
                "io"
                "log"
                "os"
                "os/exec"
        )

        import "golang.org/x/crypto/ssh/terminal"

        func main() {

                oldState, err := terminal.MakeRaw(0)
                if err != nil {
                        panic(err)
                }
                defer terminal.Restore(0, oldState)

                c := exec.Command("/bin/bash")
                f, err := pty.Start(c)
                if err != nil {
                        panic(err)
                }

                //go io.Copy(os.Stderr, f)
                go io.Copy(os.Stdout, f)
                go io.Copy(f, os.Stdin)

                c.Wait()
                log.Println("Exiting...")
        }
