### ISSUE TITLE
getting inputs

### ISSUE THREAD

**Issue by AnirudhVyas** [kr/pty#49]
I wanted to use this to run a ssh -t with a top command. The problem is I need to line up further interactive inputs - like 'm', 'h' for help, 'q' for quit etc. that top command needs for example. Here is my code - 

```go
c := exec.Command("ssh", "-t", "some_ssh_link", "'top'")
f, err := pty.Start(c)
if err != nil {
	panic(err)
}
io.Copy(os.Stdout, f)
```

Any suggestions? It can build up terminal as expected and refreshes as you'd expect but I need to line up os.Stdin with top's input.

**Comment by creack** [comment]
You don't need a pty if you want to use stdin.

This should do the trick:

```
cmd := exec.Command("ssh", "-t", "some_ssh_link", "'top'")
cmd.Stdin = os.Stdin
cmd.Stdout = os.Stdout
cmd.Stderr = os.Stderr
return cmd.Run()
```

**Comment by creack** [comment]
The issue you are having is that your terminal (stdin) is not in raw mode while the pty is.

You can use `github.com/creack/termios` to do so.

This snippet works fine on macOS 10.12.3 and linux debian 8 (jessie):

```
package main

import (
        "io"
        "log"
        "os"
        "os/exec"

        "github.com/creack/termios/raw"
        "github.com/creack/termios/win"
        "github.com/kr/pty"
)

func test() error {
        // Create arbitrary command.
        c := exec.Command("ssh", "-t", "some_ssh_link", "top")

        // Start the command with a pty.
        ptmx, err := pty.Start(c)
        if err != nil {
                return err
        }
        // Make sure to close the pty at the end.
        defer func() { _ = ptmx.Close() }()

        // Set stdin in raw mode.
        origTermios, err := raw.MakeRaw(os.Stdin.Fd())
        if err != nil {
                return err
        }
        // Defer revert the raw mode to avoid breaking the terminal.
        defer func() { _ = raw.TcSetAttr(os.Stdin.Fd(), origTermios) }() // Best effort.

        // Optional: Resize the pty to match stdin size.
        ws, err := win.GetWinsize(os.Stdin.Fd())
        if err != nil {
                return err
        }
        // As we don't resize stdin, no need to revert.
        if err := win.SetWinsize(ptmx.Fd(), ws); err != nil {
                return err
        }

        // Copy stdin to the pty and the pty to stdout.
        go func() { _, _ = io.Copy(ptmx, os.Stdin) }()
        _, _ = io.Copy(os.Stdout, ptmx)

        return nil
}

func main() {
        if err := test(); err != nil {
                log.Fatal(err)
        }
}
```

**Comment by AnirudhVyas** [comment]
Let me take a look thanks - I worked around using something like this - 
`func Execute(c *exec.Cmd) {
	f, err := pty.Start(c)
	if err != nil {
		panic(err)
	}
	go func() {
		scammer := bufio.NewScanner(os.Stdin)
		for scammer.Scan() {
			f.Write([]byte(fmt.Sprintf("%v\n", scammer.Text())))
		}
		f.Write([]byte{4}) // EOT
	}()
	io.Copy(os.Stdout, f)
}`
Seems to work as expected - only difference is I have to newline everytime I send something to terminal - a little price to pay I guess...

**Comment by AnirudhVyas** [comment]
Have to see if 

```go
c := exec.Command("ssh", "-t", "some_ssh_link", "'top'")
c.Stdin = os.Stdin
c.Stdout = os.Stdout
c.Stderr = os.Stderr
return c.Run()
```
If this would work with a terminal type application, since our specific usecase warrants telnetting to an app that performs these commands remotely...

**Comment by AnirudhVyas** [comment]
Just for others reference this works, although I am not able to figure out how to close out or exit out once the pty session is over.
```go
func main() {
	// spin off sample server to test ...
	l, _ := net.Listen("tcp", "127.0.0.1:12345")
	for {
		c, _ := l.Accept()
		go func() {
			handle(&c)
		}()
	}
}
// simple handler that runs top command
func handle(c *net.Conn) {
	cmd := exec.Command("ssh", "-t", "some_remote_host", "top")
	f, _ := pty.Start(cmd)
	go io.Copy(bufio.NewWriter(*c), f)
	go io.Copy(f, bufio.NewReader(*c))
	go io.Copy(bufio.NewWriter(*c), os.Stdin)
	cmd.Run()
}

```

**Comment by tehmoon** [comment]
@AnirudhVyas if that can help. I've been playing with this package recently.

That's like a non authenticated telnet session:

https://gist.github.com/tehmoon/7c72db32ed59f52cea3964d353f99e50

Can be tested against:
```
socat file:`tty`,raw,echo=0 tcp:x.x.x.x:1234
```
