### ISSUE TITLE
how to set timeout in the Pty

### ISSUE THREAD

**Issue by vinllen** [kr/pty#55]
I want to set a timeout in the Pty, there is a way to set a timeout in the `Conn.net` by `SetReadDeadline`, but the pty is a type of `*os.File`. So how to set the timeout？

**Comment by creack** [comment]
Where would you want a timeout for the pty? While opening the master or slave? Writing/Reading it? What would you want the timeout to do?

**Comment by kr** [comment]
Is your intention is to try to read from the terminal, and do something else if there's no input in a certain amount of time?

As you pointed out, there's no easy way to do that with an os.File like there is with net.Conn. You can try using https://golang.org/pkg/syscall/#Select on the file descriptor (https://godoc.org/os#File.Fd) to know when it's ready to read, but that is not guaranteed to work on all platforms where Go runs.
