### ISSUE TITLE
open should close the fd when there's an error

### ISSUE THREAD

**Issue by rgl** [kr/pty#56]
Isn't the code at https://github.com/kr/pty/blob/master/pty_linux.go#L10 missing a close when there's an error? e.g.:

```go
func open() (pty, tty *os.File, err error) {
	p, err := os.OpenFile("/dev/ptmx", os.O_RDWR, 0)
	if err != nil {
                p.Close() // <--- this seems to be missing on the actual code (and on the other error handlers)
		return nil, nil, err
	}
```

**Comment by cznic** [comment]
If `os.OpenFile` returns a non-nil error then the returned file cannot be considered valid. Calling `.Close` on a nil `os.File` actually works fine, but it's not documented to do so.

**Comment by rgl** [comment]
Oh, sorry, I've added that on the wrong `if`, I meant to say all the the other `if`s that come after that one, e.g.:

```go
	sname, err := ptsname(p)
	if err != nil {
                // HERE
		return nil, nil, err
	}
```
