### ISSUE TITLE
inappropriate ioctl for device

### ISSUE THREAD

**Issue by Fransebas** [kr/pty#68]
Hi I take the shell example and change little and I'm getting this error, I think the error is that I'm running the code of the example in a go routine.

     
    func InitTerminal(socket Sockets.SocketReadWriter) error {
     // Create arbitrary command.
     c := exec.Command("bash","-l")
     // Start the command with a pty.
     ptmx, err := pty.Start(c)
     if err != nil {
      return err
     }
     // Make sure to close the pty at the end.
     defer func() { _ = ptmx.Close() }() // Best effort.

     // Handle pty size.
     ch := make(chan os.Signal, 1)
     signal.Notify(ch, syscall.SIGWINCH)
     go func() {
      for range ch {
       if err := pty.InheritSize(os.Stdin, ptmx); err != nil {
        log.Printf("error resizing pty: %s", err)
       }
      }
     }()
     ch <- syscall.SIGWINCH // Initial resize.

     // Set stdin in raw mode.
            //  This is where it fails!!! *************
     oldState, err := terminal.MakeRaw(int(os.Stdin.Fd())) // <---------------*************
     if err != nil {
      panic(err)
     }
     defer func() { _ = terminal.Restore(int(os.Stdin.Fd()), oldState) }() // Best effort.

     // Copy stdin to the pty and the pty to stdout.
     go func() { _, _ = io.Copy(ptmx, socket) }()
     _, _ = io.Copy(socket, ptmx)

     return nil
    }

And this is how I call the function

    go func() {
		err := Terminal.InitTerminal(srw);
		if (err != nil){
			panic(err.Error() + ": panic initializing the terminal")
		}
    }()

**Comment by Fransebas** [comment]
Never mind, I don't know what is wrong, I change the code so that that line of code didn't run in a go routine and it also crashed.

My system is:
    MacOS Mojave 10.14.2

If you need any other info I can supply it.

**Comment by Fransebas** [comment]
I figure out what was happening, I was running the code in goland (jetbrains IDE) and for some reason it fails, but when running from the terminal it worked.

**Comment by callnothing** [comment]
same problem
`bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell`

platform:
CentOS Linux release 7.2.1511

go version:
1.8.3

process config
`
syscall.SysProcAttr{Setpgid: true}
`

**Comment by creack** [comment]
@callnothing Can you provide a sample code to reproduce the issue by any chance? Also, could you describe what you are trying to accomplish? Why trying to set pgid? Depending on the use case, it might be better to go through `pty.Open` directly instead of `pty.Start` which is a generic helper with wraps `pty.Open` with some defaults.
