### ISSUE TITLE
How to put execution results in a variable？

### ISSUE THREAD

**Issue by Mountains-and-rivers** [kr/pty#72]
i want to put result in a string  ？ do not use 	io.Copy(os.Stdout, f)。can you help me？

**Comment by creack** [comment]
Could you expand on what you are trying to achieve? The point of this library is to setup the Terminal (i.e. a device via a driver). Not really sure what would be stored in a variable.

If you are trying to get the output of an executed command, you might want to consider the raw stdlib instead:

```go
cmd := exec.Command("ls")
out, err := cmd.CombinedOutput()
[...]
```

**Comment by Mountains-and-rivers** [comment]
> Could you expand on what you are trying to achieve? The point of this library is to setup the Terminal (i.e. a device via a driver). Not really sure what would be stored in a variable.
> 
> If you are trying to get the output of an executed command, you might want to consider the raw stdlib instead:
> 
> ```go
> cmd := exec.Command("ls")
> out, err := cmd.CombinedOutput()
> [...]
> ```

i want to exec like this ：

f.Write([]byte("l"))
f.Write([]byte("s"))
f.Write([]byte("\r"))
//f.Write([]byte{4}) // EOT

**Comment by creack** [comment]
Not really sure to follow.. but you could do something like this.

```go
package main

import (
        "fmt"
        "io"
        "io/ioutil"
        "os/exec"
)

func main() {
        cmd := exec.Command("sh")
        stdin, _ := cmd.StdinPipe()
        r, w := io.Pipe()
        cmd.Stdout = w
        cmd.Stderr = w
        _ = r
        go func() {
                defer w.Close()
                _ = cmd.Run()
        }()

        _, _ = stdin.Write([]byte("l"))
        _, _ = stdin.Write([]byte("s"))
        _, _ = stdin.Write([]byte("\n"))
        _ = stdin.Close() // EOT

        result, _ := ioutil.ReadAll(r)
        fmt.Printf("%s\n", result)
}
```

Closing as it is not related to this library.

**Comment by Mountains-and-rivers** [comment]
> ```go
> package main
> 
> import (
>         "fmt"
>         "io"
>         "io/ioutil"
>         "os/exec"
> )
> 
> func main() {
>         cmd := exec.Command("sh")
>         stdin, _ := cmd.StdinPipe()
>         r, w := io.Pipe()
>         cmd.Stdout = w
>         cmd.Stderr = w
>         _ = r
>         go func() {
>                 defer w.Close()
>                 _ = cmd.Run()
>         }()
> 
>         _, _ = stdin.Write([]byte("l"))
>         _, _ = stdin.Write([]byte("s"))
>         _, _ = stdin.Write([]byte("\n"))
>         _ = stdin.Close() // EOT
> 
>         result, _ := ioutil.ReadAll(r)
>         fmt.Printf("%s\n", result)
> }
> ```

thank you,but this can not keep linux terminal style 。like this:
glide.lock      glide.yaml      test.go         vendor

not

glide.lock
glide.yaml
test.go
vendor


i did like this:

package main

import (
	"fmt"
	"os"
	"os/exec"
	"time"

	"github.com/kr/pty"
)

func main() {
	c := exec.Command("/bin/bash", "-l")
	f, err := pty.Start(c)
	c.Env = os.Environ()
	c.Env = append(c.Env, "LANG=en_US.UTF-8", "LC_ALL=en_US.UTF-8")
	if err != nil {
		panic(err)
	}

	go func() {
		f.Write([]byte("l"))
		f.Write([]byte("s"))
		f.Write([]byte("\r"))
		//f.Write([]byte{4}) // EOT

	}()

	time.Sleep(2 * time.Second)
	//var file *os.File
	//io.Copy(file, f)
	buf := make([]byte, 1024)
	f.Read(buf)
	var strf = string(buf)
	//var a = strings.Split(strf, "\n")
	fmt.Println(strf)
}

but it output  'ls'  and a '\n'  ,i do not need them,only   'glide.lock      glide.yaml      test.go         vendor'  is 
tisfactory output。

**Comment by Mountains-and-rivers** [comment]
![10_32_23__03_29_2019](https://user-images.githubusercontent.com/15889219/55205477-ffbade80-520d-11e9-97f3-f3ce11f77a87.jpg)
