### ISSUE TITLE
Please release v1.1.5

### ISSUE THREAD

**Issue by myitcv** [kr/pty#83]
Following the discussion in https://github.com/golang/go/issues/32527#issuecomment-500859320, it appears that https://github.com/kr/pty/commit/b6e1bdd4a4f88614e0c6e5e8089c7abed98aae17 is required in order to work with `pty` using Go tip.

Please can I therefore ask you to tag `v1.1.5`?

For now, I can use `master`.

But when `go1.13beta1` is released, however, an official semver version will be more convenient for people whose setup will be broken.

**Comment by creack** [comment]
Done
